apiVersion: v1
kind: Pod
metadata:
  name: busyboxab
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy1
    command:
    - sleep 
    - "3600"
    volumeMounts:
    - mountPath: /dir
      name: myvolume
  volumes:
  - name: myvolume
    emptyDir: {}
